context:
  name: pokeget
  version: "1.6.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/talwat/${{ name }}-rs/archive/refs/tags/${{ version }}.tar.gz
    sha256: aad069bdd466054672e28e71906105dd3fa1dd515d5a09b3f7d64d1ca367ee05
  # update this if the SHA changed upstream: https://github.com/talwat/pokeget-rs/tree/main/data
  - url: https://github.com/msikma/pokesprite/archive/c5aaa610ff2acdf7fd8e2dccd181bca8be9fcb3e.tar.gz
    sha256: d0d420bd0550f6d21fa652c6e0d82d2c2c3052dc4f96f85c4b74d5dc90bcc8cd
    target_directory: data/pokesprite

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pokeget --help

about:
  homepage: https://github.com/talwat/pokeget-rs
  summary: A better rust version of pokeget
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/talwat/pokeget-rs

extra:
  recipe-maintainers:
    - pavelzw
